name: Build and Publish Pre-commit Container

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.precommit"
      - ".github/workflows/build-precommit-image.yml"
  pull_request:
    paths:
      - "Dockerfile.precommit"
      - ".github/workflows/build-precommit-image.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/pre-commit

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build Docker image locally
        id: build-local
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.precommit
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Manual Trivy Setup
        id: setup-trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.67.2

      - name: Run Trivy vulnerability scanner (SARIF)
        id: trivy-scan
        uses: aquasecurity/trivy-action@0.33.0
        with:
          skip-setup-trivy: true
          trivy-config: trivy.yaml
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "0"

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"
        if: always()

      - name: Run Trivy vulnerability scanner (Table)
        uses: aquasecurity/trivy-action@0.33.0
        with:
          skip-setup-trivy: true
          trivy-config: trivy.yaml
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: "table"
          severity: "CRITICAL,HIGH,MEDIUM"
        if: success()

      - name: Build and push multi-arch Docker image
        id: build-push
        if: github.event_name != 'pull_request' && success()
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.precommit
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.meta.outputs.tags[1] }}
          artifact-name: sbom-precommit.spdx
          output-file: sbom-precommit.spdx.json
        if: github.event_name != 'pull_request' && success()

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v6
        with:
          name: sbom-precommit
          path: sbom-precommit.spdx.json
        if: github.event_name != 'pull_request' && success()

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0
        with:
          cosign-release: "v3.0.2"

      - name: Check install!
        run: cosign version

      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      - name: Sign image with a cosign
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag} "
          done
          cosign sign --yes ${images}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          # COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          # COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          # DIGEST: ${{ steps.build-push.outputs.digest }}

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
